Repository hyperion-project/hyperion.ng, pull requests merged in 2020-10, with the labels that each got.

#1037 Allow 8-LED configuration for KarateLight
  CHANGELOG.md
  libsrc/leddevice/dev_serial/LedDeviceKarate.cpp
Labels: Improvements

#1047 Fix issue #909 - "Set many LEDs on the horizontal bottom crashes Hyperion"
  include/utils/hyperion.h
Labels: bug

#1049 Fix #1015 - Fix Lightpack / Remove Multi-Lightpack
  CHANGELOG.md
  assets/webconfig/js/content_leds.js
  libsrc/leddevice/LedDeviceSchemas.qrc
  libsrc/leddevice/dev_hid/LedDeviceLightpack.cpp
  libsrc/leddevice/dev_hid/LedDeviceLightpack.h
  libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.cpp
  libsrc/leddevice/dev_hid/LedDeviceMultiLightpack.h
  libsrc/leddevice/schemas/schema-multilightpack.json
Labels: bug

#1044 Fix color calibration for Kodi 18 (Fixes #771)
  CHANGELOG.md
  assets/webconfig/i18n/en.json
  assets/webconfig/js/wizard.js
Labels: bug

#1045 Additional information on system used
  CHANGELOG.md
  assets/webconfig/content/about.html
  assets/webconfig/js/content_logging.js
  include/utils/SysInfo.h
  libsrc/api/JsonAPI.cpp
  libsrc/utils/SysInfo.cpp
  src/hyperiond/main.cpp
Labels: Enhancements

#1067 Change links from http to https
  README.md
  assets/webconfig/content/about.html
  assets/webconfig/content/support.html
Labels: hacktoberfest-accepted
