Repository hyperion-project/hyperion.ng, pull requests merged in 2020-11, with the labels that each got.

#1042 Fix for sk9822 frame sufix
  libsrc/leddevice/dev_spi/LedDeviceSK9822.cpp
Labels: bug

#1046 Read-Only Configuration-Database support
  CHANGELOG.md
  assets/webconfig/content/about.html
  assets/webconfig/js/content_colors.js
  assets/webconfig/js/content_dashboard.js
  assets/webconfig/js/content_effects.js
  assets/webconfig/js/content_effectsconfigurator.js
  assets/webconfig/js/content_general.js
  assets/webconfig/js/content_grabber.js
  assets/webconfig/js/content_index.js
  assets/webconfig/js/content_leds.js
  assets/webconfig/js/content_logging.js
  assets/webconfig/js/content_network.js
  assets/webconfig/js/content_webconfig.js
  assets/webconfig/js/hyperion.js
  assets/webconfig/js/settings.js
  assets/webconfig/js/wizard.js
  include/api/API.h
  include/db/AuthTable.h
  include/db/DBManager.h
  include/db/InstanceTable.h
  include/db/MetaTable.h
  include/hyperion/AuthManager.h
  include/hyperion/Hyperion.h
  include/hyperion/HyperionIManager.h
  include/hyperion/SettingsManager.h
  libsrc/api/API.cpp
  libsrc/api/JsonAPI.cpp
  libsrc/db/DBManager.cpp
  libsrc/hyperion/AuthManager.cpp
  libsrc/hyperion/Hyperion.cpp
  libsrc/hyperion/HyperionIManager.cpp
  libsrc/hyperion/SettingsManager.cpp
  src/hyperiond/hyperiond.cpp
  src/hyperiond/hyperiond.h
  src/hyperiond/main.cpp
Labels: Enhancements

#1070 New LED Device - Cololight
  CHANGELOG.md
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_leds.js
  assets/webconfig/js/wizard.js
  include/leddevice/LedDevice.h
  libsrc/leddevice/LedDevice.cpp
  libsrc/leddevice/LedDeviceSchemas.qrc
  libsrc/leddevice/dev_net/LedDeviceCololight.cpp
  libsrc/leddevice/dev_net/LedDeviceCololight.h
  libsrc/leddevice/dev_net/ProviderUdp.cpp
  libsrc/leddevice/dev_net/ProviderUdp.h
  libsrc/leddevice/schemas/schema-cololight.json
Labels: new feature

#1073 Improve Platform Grabber UI
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_grabber.js
  config/hyperion.config.json.commented
  config/hyperion.config.json.default
  include/hyperion/GrabberWrapper.h
  libsrc/api/JsonAPI.cpp
  libsrc/hyperion/GrabberWrapper.cpp
  libsrc/hyperion/SettingsManager.cpp
  libsrc/hyperion/schema/schema-framegrabber.json
Labels: Improvements, bug

#1078 Add additional system info
  CHANGELOG.md
  assets/webconfig/content/about.html
  assets/webconfig/js/content_logging.js
  include/utils/SysInfo.h
  libsrc/api/JsonAPI.cpp
  libsrc/utils/CMakeLists.txt
  libsrc/utils/SysInfo.cpp
  src/hyperiond/hyperiond.cpp
  src/hyperiond/main.cpp
Labels: new feature

#1079 Fix hostname/domain split
  libsrc/leddevice/dev_net/LedDeviceCololight.cpp
  libsrc/ssdp/SSDPDiscover.cpp
Labels: bug

#1082 Fix #1045
  src/hyperiond/main.cpp
Labels: bug
