Repository hyperion-project/hyperion.ng, pull requests merged in 2020-06, with the labels that each got.

#812 Improve language selection usability
  assets/webconfig/content/about.html
  assets/webconfig/css/bootstrap-select.min.css
  assets/webconfig/css/darkMode.css
  assets/webconfig/css/hyperion.css
  assets/webconfig/index.html
  assets/webconfig/js/content_index.js
  assets/webconfig/js/lib/bootstrap-select.min.js
  assets/webconfig/js/settings.js
  assets/webconfig/js/ui_utils.js
  include/utils/Logger.h
Labels: Enhancements

#830 Suppress default password warning
  assets/webconfig/i18n/de.json
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_index.js
Labels: new feature

#842 feat(webui): Add French, Turkish, Vietnamese & translation update
  CHANGELOG.md
  assets/webconfig/i18n/cs.json
  assets/webconfig/i18n/de.json
  assets/webconfig/i18n/en.json
  assets/webconfig/i18n/es.json
  assets/webconfig/i18n/fr.json
  assets/webconfig/i18n/it.json
  assets/webconfig/i18n/nl.json
  assets/webconfig/i18n/pl.json
  assets/webconfig/i18n/ro.json
  assets/webconfig/i18n/sv.json
  assets/webconfig/i18n/tr.json
  assets/webconfig/i18n/vi.json
  assets/webconfig/js/settings.js
Labels: Language update

#833 Update CHANGELOG.md
  CHANGELOG.md
Labels: CHANGELOG

#837 use QSerialPortInfo to detect presence of a serial port (fix #836)
  libsrc/leddevice/dev_serial/ProviderRs232.cpp
Labels: Enhancements

#841 Improve utils code style
  include/utils/FileUtils.h
  include/utils/GlobalSignals.h
  include/utils/NetUtils.h
  include/utils/RgbChannelAdjustment.h
  include/utils/RgbTransform.h
  include/utils/hyperion.h
  libsrc/utils/ColorSys.cpp
  libsrc/utils/FileUtils.cpp
  libsrc/utils/ImageResampler.cpp
  libsrc/utils/Logger.cpp
  libsrc/utils/Process.cpp
  libsrc/utils/Profiler.cpp
  libsrc/utils/RgbToRgbw.cpp
  libsrc/utils/RgbTransform.cpp
  libsrc/utils/SysInfo.cpp
Labels: Improvements

#844 Delay M-SEARCH response by a random value according to MX header
  libsrc/ssdp/SSDPDiscover.cpp
  libsrc/ssdp/SSDPHandler.cpp
  libsrc/ssdp/SSDPServer.cpp
Labels: Enhancements

#845 Fix broken link to CompileHowto in documentation
  CONTRIBUTING.md
Labels: Typo fix

#846 Fixes #668 : Fix delete order of threads
  CHANGELOG.md
  libsrc/python/PythonInit.cpp
  src/hyperiond/hyperiond.cpp
Labels: HotFix

#848 Show thread names in GDB for better debugging
  libsrc/hyperion/HyperionIManager.cpp
  libsrc/leddevice/LedDeviceWrapper.cpp
  src/hyperion-aml/AmlogicWrapper.cpp
  src/hyperiond/hyperiond.cpp
Labels: Enhancements

#850 Fix leaking active events and a potential crash during quit
  libsrc/effectengine/EffectEngine.cpp
Labels: HotFix

#843 Get process IDs by iterating /proc
  src/hyperion-aml/hyperion-aml.cpp
  src/hyperion-remote/JsonConnection.cpp
  src/hyperion-v4l2/ScreenshotHandler.cpp
  src/hyperion-x11/hyperion-x11.cpp
  src/hyperiond/detectProcess.h
  src/hyperiond/main.cpp
  src/hyperiond/systray.cpp
Labels: Enhancements
