Repository hyperion-project/hyperion.ng, pull requests merged in 2020-02, with the labels that each got.

#636 Package creation with dependencies
  .azure.yml
  .ci/ci_build.sh
  .vscode/settings.json
  CMakeLists.txt
  HyperionConfig.h.in
  README.md
  bin/create_all_releases.sh
  bin/create_release.sh
  bin/scripts/docker-compile.sh
  cmake/FindGitVersion.cmake
  cmake/packages.cmake
  cmake/version.cmake
  libsrc/api/JsonAPI.cpp
  libsrc/python/PythonInit.cpp
  resources/CMakeLists.txt
  src/hyperiond/CMakeLists.txt
  src/hyperiond/main.cpp
  test/jsonchecks/version.py
  version
  version.json
Labels: WIP

#689 Resolved SSL/Avahi problem in Packages
  src/hyperiond/CMakeLists.txt
Labels: HotFix

#675 Swedish Translation
  assets/webconfig/i18n/de.json
  assets/webconfig/i18n/en.json
  assets/webconfig/i18n/sv.json
  assets/webconfig/js/settings.js
Labels: New Language

#702 CI - Artifacts for faster testing
  .ci/ci_build.sh
  .github/workflows/cleanup.yml
  .github/workflows/pull-request.yml
  .github/workflows/push-master.yml
  .vscode/settings.json
  src/hyperiond/CMakeLists.txt
  version
Labels: WIP
