Repository hyperion-project/hyperion.ng, pull requests merged in 2020-05, with the labels that each got.

#778 Toggle-Buttons for Component Remote Control (#677)
  assets/webconfig/content/about.html
  assets/webconfig/css/bootstrap-toggle.min.css
  assets/webconfig/css/hyperion.css
  assets/webconfig/index.html
  assets/webconfig/js/content_index.js
  assets/webconfig/js/content_remote.js
  assets/webconfig/js/lib/bootstrap-toggle.min.js
Labels: Waiting For Review

#592 add Hue EntertainmentAPI + Forwarder & other Fixes
  CMakeLists.txt
  CompileHowto.md
  CrossCompileHowto.md
  assets/webconfig/i18n/de.json
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_general.js
  assets/webconfig/js/content_grabber.js
  assets/webconfig/js/content_index.js
  assets/webconfig/js/content_leds.js
  assets/webconfig/js/ledsim.js
  assets/webconfig/js/lib/jquery.i18n.js
  assets/webconfig/js/lib/jquery.i18n.language.js
  assets/webconfig/js/settings.js
  assets/webconfig/js/streamer.js
  assets/webconfig/js/ui_utils.js
  assets/webconfig/js/wizard.js
  bin/compile.sh
  bin/remove_hyperion.sh
  cmake/Findmbedtls.cmake
  dependencies/CMakeLists-mbedtls.txt.in
  dependencies/CMakeLists.txt
  include/leddevice/LedDevice.h
  include/ssdp/SSDPHandler.h
  libsrc/hyperion/HyperionIManager.cpp
  libsrc/hyperion/MessageForwarder.cpp
  libsrc/leddevice/CMakeLists.txt
  libsrc/leddevice/LedDevice.cpp
  libsrc/leddevice/dev_net/LedDeviceNanoleaf.cpp
  libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
  libsrc/leddevice/dev_net/LedDevicePhilipsHue.h
  libsrc/leddevice/dev_net/ProviderUdp.cpp
  libsrc/leddevice/dev_net/ProviderUdpSSL.cpp
  libsrc/leddevice/dev_net/ProviderUdpSSL.h
  libsrc/leddevice/schemas/schema-philipshue.json
  libsrc/ssdp/SSDPHandler.cpp
  src/hyperiond/hyperiond.cpp
  src/hyperiond/hyperiond.h
Labels: Waiting For Review, new feature

#799 Fix Rewrite-/LatchTime LedDevice definitions (#785)
  assets/webconfig/i18n/en.json
  config/hyperion.config.json.default
  include/utils/jsonschema/QJsonSchemaChecker.h
  libsrc/hyperion/schema/schema-device.json
  libsrc/leddevice/dev_spi/ProviderSpi.cpp
  libsrc/leddevice/schemas/schema-adalight.json
  libsrc/leddevice/schemas/schema-apa102.json
  libsrc/leddevice/schemas/schema-apa104.json
  libsrc/leddevice/schemas/schema-artnet.json
  libsrc/leddevice/schemas/schema-atmo.json
  libsrc/leddevice/schemas/schema-atmoorb.json
  libsrc/leddevice/schemas/schema-dmx.json
  libsrc/leddevice/schemas/schema-e131.json
  libsrc/leddevice/schemas/schema-fadecandy.json
  libsrc/leddevice/schemas/schema-file.json
  libsrc/leddevice/schemas/schema-h801.json
  libsrc/leddevice/schemas/schema-hyperionusbasp.json
  libsrc/leddevice/schemas/schema-karate.json
  libsrc/leddevice/schemas/schema-lightpack.json
  libsrc/leddevice/schemas/schema-lpd6803.json
  libsrc/leddevice/schemas/schema-lpd8806.json
  libsrc/leddevice/schemas/schema-multilightpack.json
  libsrc/leddevice/schemas/schema-p9813.json
  libsrc/leddevice/schemas/schema-paintpack.json
  libsrc/leddevice/schemas/schema-piblaster.json
  libsrc/leddevice/schemas/schema-rawhid.json
  libsrc/leddevice/schemas/schema-sedu.json
  libsrc/leddevice/schemas/schema-sk6812spi.json
  libsrc/leddevice/schemas/schema-sk6822spi.json
  libsrc/leddevice/schemas/schema-tinkerforge.json
  libsrc/leddevice/schemas/schema-tpm2.json
  libsrc/leddevice/schemas/schema-tpm2net.json
  libsrc/leddevice/schemas/schema-udpraw.json
  libsrc/leddevice/schemas/schema-ws2801.json
  libsrc/leddevice/schemas/schema-ws2812spi.json
  libsrc/leddevice/schemas/schema-ws281x.json
  libsrc/utils/jsonschema/QJsonSchemaChecker.cpp
Labels: REFACTORING
