Repository hyperion-project/hyperion.ng, pull requests merged in 2021-05, with the labels that each got.

#1236 New languages - Portuguese (Std/Brazil) & Norwegian (Bokmål)
  assets/webconfig/i18n/en.json
  assets/webconfig/i18n/nb.json
  assets/webconfig/i18n/pt-br.json
  assets/webconfig/i18n/pt.json
  assets/webconfig/index.html
  assets/webconfig/js/lib/jquery.i18n/CLDRPluralRuleParser.js
  assets/webconfig/js/lib/jquery.i18n/jquery.i18n.emitter.bidi.js
  assets/webconfig/js/lib/jquery.i18n/jquery.i18n.emitter.js
  assets/webconfig/js/lib/jquery.i18n/jquery.i18n.fallbacks.js
  assets/webconfig/js/lib/jquery.i18n/jquery.i18n.js
  assets/webconfig/js/lib/jquery.i18n/jquery.i18n.language.js
  assets/webconfig/js/lib/jquery.i18n/jquery.i18n.messagestore.js
  assets/webconfig/js/lib/jquery.i18n/jquery.i18n.parser.js
  assets/webconfig/js/lib/jquery.i18n/languages/bs.js
  assets/webconfig/js/lib/jquery.i18n/languages/dsb.js
  assets/webconfig/js/lib/jquery.i18n/languages/fi.js
  assets/webconfig/js/lib/jquery.i18n/languages/ga.js
  assets/webconfig/js/lib/jquery.i18n/languages/he.js
  assets/webconfig/js/lib/jquery.i18n/languages/hsb.js
  assets/webconfig/js/lib/jquery.i18n/languages/hu.js
  assets/webconfig/js/lib/jquery.i18n/languages/hy.js
  assets/webconfig/js/lib/jquery.i18n/languages/la.js
  assets/webconfig/js/lib/jquery.i18n/languages/ml.js
  assets/webconfig/js/lib/jquery.i18n/languages/os.js
  assets/webconfig/js/lib/jquery.i18n/languages/ru.js
  assets/webconfig/js/lib/jquery.i18n/languages/sl.js
  assets/webconfig/js/lib/jquery.i18n/languages/uk.js
  assets/webconfig/js/settings.js
Labels: Language update

#1244 WebUI English grammar improvement
  assets/webconfig/i18n/en.json
Labels: Language update

#1241 Minor Updates
  include/hyperion/ImageToLedsMap.h
  libsrc/hyperion/Hyperion.cpp
  libsrc/hyperion/ImageProcessor.cpp
  libsrc/hyperion/ImageToLedsMap.cpp
  libsrc/leddevice/dev_other/LedDeviceFile.cpp
Labels: Improvements, bug

#1250 Fix #1216 - Clear All occasionally does not work
  libsrc/hyperion/PriorityMuxer.cpp
Labels: bug

#1246 Serial-Devices - Add udev support
  assets/webconfig/js/content_leds.js
  libsrc/leddevice/dev_serial/ProviderRs232.cpp
  libsrc/leddevice/dev_serial/ProviderRs232.h
Labels: Enhancements, bug
