Repository hyperion-project/hyperion.ng, pull requests merged in 2021-07, with the labels that each got.

#1257 Add Supported Platforms documention
  README.md
  doc/development/CompileHowto.md
  doc/development/Hyperion-platforms_supported.xlsx
  doc/development/LedDevice_Flows.drawio
  doc/development/LedDevice_Flows.png
  doc/development/SupportedPlatforms.md
Labels: Improvements

#1265 Debian/Ubuntu APT
  .github/workflows/apt.json
  .github/workflows/apt.yml
  .github/workflows/push-master.yml
  .github/workflows/release.yml
  CMakeLists.txt
  Installation.md
  cmake/desktop/hyperiond_128.png
  cmake/osxbundle/Hyperion.icns
  cmake/packages.cmake
  cmake/version.cmake
  debian/control.in
  debian/distributions
  debian/rules
  src/hyperiond/CMakeLists.txt
Labels: Enhancements

#1258 websocket crashes fixed
  libsrc/webserver/WebSocketClient.cpp
Labels: bug

#1272 Prepare for Alpha.10
  CHANGELOG.md
  assets/webconfig/content/login.html
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_colors.js
  assets/webconfig/js/content_dashboard.js
  assets/webconfig/js/content_grabber.js
  assets/webconfig/js/content_leds.js
  assets/webconfig/js/ledsim.js
  assets/webconfig/js/settings.js
  assets/webconfig/js/ui_utils.js
  cmake/Dependencies.cmake
  cmake/nsis/header.bmp
  libsrc/grabber/amlogic/AmlogicGrabber.cpp
  libsrc/grabber/directx/DirectXGrabber.cpp
  libsrc/grabber/dispmanx/DispmanxFrameGrabber.cpp
  libsrc/grabber/framebuffer/FramebufferFrameGrabber.cpp
  libsrc/grabber/osx/OsxFrameGrabber.cpp
  libsrc/grabber/qt/QtGrabber.cpp
  libsrc/grabber/x11/X11Grabber.cpp
  libsrc/grabber/xcb/XcbGrabber.cpp
  libsrc/hyperion/GrabberWrapper.cpp
  libsrc/hyperion/SettingsManager.cpp
  libsrc/hyperion/schema/schema-framegrabber.json
Labels: CHANGELOG

#1285 Amlogic updates
  assets/webconfig/i18n/en.json
  libsrc/api/JsonAPI.cpp
  libsrc/grabber/amlogic/AmlogicGrabber.cpp
  libsrc/grabber/amlogic/Amvideocap.h
Labels: Improvements

#1279 Fix Philips Hue and AtmoOrb wizards
  assets/webconfig/js/wizard.js
  libsrc/leddevice/dev_net/ProviderUdpSSL.cpp
Labels: bug
