Repository hyperion-project/hyperion.ng, pull requests merged in 2021-02, with the labels that each got.

#1186 Fix #1131 - Have Global (Grabber) settings reflected correctly in non-default instances
  include/hyperion/SettingsManager.h
  libsrc/hyperion/SettingsManager.cpp
Labels: bug

#1188 Fix #1186 & UI last instance error
  assets/webconfig/js/ui_utils.js
  libsrc/hyperion/SettingsManager.cpp
Labels: bug

#1146 Proto*: fix Error macro conflict
  libsrc/protoserver/ProtoClientConnection.cpp
  libsrc/protoserver/ProtoClientConnection.h
  libsrc/protoserver/ProtoServer.cpp
Labels: bug

#1191 DirectX9 display change
  cmake/Dependencies.cmake
  include/grabber/DirectXGrabber.h
  libsrc/grabber/directx/DirectXGrabber.cpp
Labels: bug

#1163 Custom Effects - Clean-ups and Enhancements
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_effectsconfigurator.js
  include/effectengine/EffectFileHandler.h
  libsrc/api/JsonAPI.cpp
  libsrc/effectengine/EffectFileHandler.cpp
  libsrc/webserver/WebSocketClient.cpp
  libsrc/webserver/WebSocketClient.h
Labels: Enhancements, REFACTORING

#1162 Update Documentation
  docs/docs/de/user/Installation.md
  docs/docs/en/user/Installation.md
  docs/docs/en/user/LedDevices.md
Labels: Improvements

#1139 Adalight - Fix LED Num for non analogue output
  assets/firmware/arduino/adalight/adalight.ino
Labels: bug

#1128 Correct total packet count in tpm2net implementation (fix #1127)
  CHANGELOG.md
  libsrc/leddevice/dev_net/LedDeviceTpm2net.cpp
Labels: bug
