Repository hyperion-project/hyperion.ng, pull requests merged in 2021-04, with the labels that each got.

#1230 Fixes: #1229
  CHANGELOG.md
  assets/webconfig/i18n/en.json
Labels: bug

#1164 Dynamic Device Selection/Configuration
  .github/workflows/pull-request.yml
  assets/webconfig/content/conf_leds.html
  assets/webconfig/i18n/en.json
  assets/webconfig/index.html
  assets/webconfig/js/content_colors.js
  assets/webconfig/js/content_index.js
  assets/webconfig/js/content_leds.js
  assets/webconfig/js/ui_utils.js
  assets/webconfig/js/wizard.js
  cmake/debian/postinst
  cmake/packages.cmake
  cmake/rpm/postinst
  include/hyperion/SettingsManager.h
  include/leddevice/LedDevice.h
  include/utils/version.hpp
  libsrc/hyperion/Hyperion.cpp
  libsrc/hyperion/SettingsManager.cpp
  libsrc/hyperion/schema/schema-device.json
  libsrc/hyperion/schema/schema-general.json
  libsrc/hyperion/schema/schema-ledConfig.json
  libsrc/leddevice/LedDevice.cpp
  libsrc/leddevice/dev_net/LedDeviceWled.cpp
  libsrc/leddevice/dev_net/LedDeviceWled.h
  libsrc/leddevice/dev_net/LedDeviceYeelight.cpp
  libsrc/leddevice/dev_other/LedDevicePiBlaster.cpp
  libsrc/leddevice/dev_other/LedDevicePiBlaster.h
  libsrc/leddevice/dev_serial/ProviderRs232.cpp
  libsrc/leddevice/dev_serial/ProviderRs232.h
  libsrc/leddevice/dev_spi/ProviderSpi.cpp
  libsrc/leddevice/dev_spi/ProviderSpi.h
  libsrc/leddevice/schemas/schema-adalight.json
  libsrc/leddevice/schemas/schema-apa102.json
  libsrc/leddevice/schemas/schema-apa104.json
  libsrc/leddevice/schemas/schema-atmoorb.json
  libsrc/leddevice/schemas/schema-cololight.json
  libsrc/leddevice/schemas/schema-lpd6803.json
  libsrc/leddevice/schemas/schema-lpd8806.json
  libsrc/leddevice/schemas/schema-nanoleaf.json
  libsrc/leddevice/schemas/schema-p9813.json
  libsrc/leddevice/schemas/schema-philipshue.json
  libsrc/leddevice/schemas/schema-sk6812spi.json
  libsrc/leddevice/schemas/schema-sk6822spi.json
  libsrc/leddevice/schemas/schema-sk9822.json
  libsrc/leddevice/schemas/schema-wled.json
  libsrc/leddevice/schemas/schema-ws2801.json
  libsrc/leddevice/schemas/schema-ws2812spi.json
  libsrc/leddevice/schemas/schema-yeelight.json
  src/hyperiond/hyperiond.cpp
Labels: Improvements, New Feature Request

#1226 Stop background effect, when it gets out of scope
  include/hyperion/BGEffectHandler.h
Labels: Improvements

#1223 UI System Log - Fixes and enhancements
  assets/webconfig/content/about.html
  assets/webconfig/content/conf_logging.html
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_index.js
  assets/webconfig/js/content_logging.js
  assets/webconfig/js/content_remote.js
  assets/webconfig/js/ledsim.js
  assets/webconfig/js/ui_utils.js
Labels: Improvements, bug
