Repository hyperion-project/hyperion.ng, pull requests merged in 2022-04, with the labels that each got.

#1450 Fix Iterator issue on Windows
  libsrc/hyperion/PriorityMuxer.cpp
Labels: Bug

#1457 add hardware support
  README.md
Labels: Improvements

#1444 WebUI fixes & Draggable LEDs
  3RD_PARTY_LICENSES
  README.md
  assets/webconfig/content/conf_leds.html
  assets/webconfig/content/conf_logging.html
  assets/webconfig/css/animate.min.css
  assets/webconfig/css/darkMode.css
  assets/webconfig/css/hyperion.css
  assets/webconfig/i18n/de.json
  assets/webconfig/i18n/en.json
  assets/webconfig/index.html
  assets/webconfig/js/content_leds.js
  assets/webconfig/js/content_logging.js
  assets/webconfig/js/ledsim.js
  assets/webconfig/js/lib/leader-line.min.js
  assets/webconfig/js/lib/plain-draggable.min.js
  assets/webconfig/js/ui_utils.js
  assets/webconfig/js/wizard.js
Labels: New Feature Request
