Repository hyperion-project/hyperion.ng, pull requests merged in 2024-03, with the labels that each got.

#1711 add missing ENABLE_MDNS in hyperiond.cpp
  src/hyperiond/hyperiond.cpp
Labels: Bug

#1701 Matrix Layout enhancements
  CHANGELOG.md
  assets/webconfig/content/conf_leds.html
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_leds.js
  cmake/package-scripts/postinst
  include/blackborder/BlackBorderDetector.h
  libsrc/hyperion/schema/schema-ledConfig.json
Labels: New Feature Request

#1717 Fix #1714
  include/grabber/amlogic/AmlogicWrapper.h
  libsrc/grabber/amlogic/AmlogicWrapper.cpp
  libsrc/grabber/directx/DirectXWrapper.cpp
  libsrc/grabber/dispmanx/DispmanxWrapper.cpp
  libsrc/grabber/framebuffer/FramebufferWrapper.cpp
  libsrc/grabber/osx/OsxWrapper.cpp
  libsrc/grabber/qt/QtWrapper.cpp
  libsrc/grabber/x11/X11Wrapper.cpp
  libsrc/grabber/xcb/XcbWrapper.cpp
Labels: Bug

#1718 Fix Kodi Color Calibration, Refactor Wizards
  assets/webconfig/js/content_huebridge.js
  assets/webconfig/js/content_leds.js
  assets/webconfig/js/ui_utils.js
  assets/webconfig/js/wizard.js
  assets/webconfig/js/wizards/LedDevice_atmoorb.js
  assets/webconfig/js/wizards/LedDevice_nanoleaf.js
  assets/webconfig/js/wizards/LedDevice_philipshue.js
  assets/webconfig/js/wizards/LedDevice_utils.js
  assets/webconfig/js/wizards/LedDevice_yeelight.js
  assets/webconfig/js/wizards/colorCalibrationKodiWizard.js
  assets/webconfig/js/wizards/rgbByteOrderWizard.js
Labels: Bug, REFACTORING

#1695 Add workaround for issue #1692
  libsrc/webserver/StaticFileServing.cpp
Labels: No-Hyperion Issue
