Repository hyperion-project/hyperion.ng, pull requests merged in 2024-05, with the labels that each got.

#1737 Disable Identify for same serial device
  assets/webconfig/js/content_leds.js
Labels: Improvements

#1738 New Language + Fixes
  assets/webconfig/i18n/bg.json
  assets/webconfig/i18n/en.json
  assets/webconfig/js/languages.js
Labels: Language update

#1741 Fix #1688 - Fragmented http-Headers
  libsrc/webserver/QtHttpClientWrapper.cpp
  libsrc/webserver/QtHttpClientWrapper.h
Labels: Bug

#1743 Fix Philip Hue APIv2 support without Entertainment group defined
  CHANGELOG.md
  assets/webconfig/js/wizards/LedDevice_philipshue.js
  libsrc/leddevice/LedDeviceWrapper.cpp
  libsrc/leddevice/dev_net/LedDevicePhilipsHue.cpp
  libsrc/leddevice/dev_net/ProviderRestApi.cpp
Labels: Bug

#1745 Windows: Add a DDA grabber for much better performance
  CHANGELOG.md
  CMakeLists.txt
  HyperionConfig.h.in
  doc/development/CompileHowto.md
  include/grabber/GrabberConfig.h
  include/grabber/dda/DDAGrabber.h
  include/grabber/dda/DDAWrapper.h
  libsrc/api/JsonInfo.cpp
  libsrc/grabber/CMakeLists.txt
  libsrc/grabber/dda/CMakeLists.txt
  libsrc/grabber/dda/DDAGrabber.cpp
  libsrc/grabber/dda/DDAWrapper.cpp
  libsrc/hyperion/GrabberWrapper.cpp
  src/hyperiond/CMakeLists.txt
  src/hyperiond/hyperiond.cpp
  src/hyperiond/hyperiond.h
Labels: New Feature Request

#1746 Implement ftdi led device - 2
  .github/workflows/codeql.yml
  .github/workflows/qt5_6.yml
  CHANGELOG.md
  CMakeLists.txt
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_leds.js
  doc/development/CompileHowto.md
  include/utils/RgbToRgbw.h
  libsrc/leddevice/CMakeLists.txt
  libsrc/leddevice/LedDeviceSchemas.qrc
  libsrc/leddevice/dev_ftdi/LedDeviceAPA102_ftdi.cpp
  libsrc/leddevice/dev_ftdi/LedDeviceAPA102_ftdi.h
  libsrc/leddevice/dev_ftdi/LedDeviceSk6812_ftdi.cpp
  libsrc/leddevice/dev_ftdi/LedDeviceSk6812_ftdi.h
  libsrc/leddevice/dev_ftdi/LedDeviceWs2812_ftdi.cpp
  libsrc/leddevice/dev_ftdi/LedDeviceWs2812_ftdi.h
  libsrc/leddevice/dev_ftdi/ProviderFtdi.cpp
  libsrc/leddevice/dev_ftdi/ProviderFtdi.h
  libsrc/leddevice/schemas/schema-apa102_ftdi.json
  libsrc/leddevice/schemas/schema-sk6812_ftdi.json
  libsrc/leddevice/schemas/schema-sk6812spi.json
  libsrc/leddevice/schemas/schema-ws2812_ftdi.json
  libsrc/leddevice/schemas/schema-ws281x.json
  libsrc/utils/RgbToRgbw.cpp
Labels: New Feature Request
