Repository hyperion-project/hyperion.ng, pull requests merged in 2025-03, with the labels that each got.

#1826 Implemented 16Bit HD108-Leds in HyperionNG
  assets/webconfig/js/content_leds.js
  libsrc/leddevice/LedDeviceSchemas.qrc
  libsrc/leddevice/dev_spi/LedDeviceHD108.cpp
  libsrc/leddevice/dev_spi/LedDeviceHD108.h
  libsrc/leddevice/schemas/schema-hd108.json
Labels: New Feature Request

#1844 Store a list of arrays at each location so duplicates aren't lost
  CHANGELOG.md
  libsrc/leddevice/dev_net/LedDeviceNanoleaf.cpp
Labels: Improvements

#1846 Support a configurable grabber inactive detection time interval
  CHANGELOG.md
  CMakeLists.txt
  assets/webconfig/i18n/en.json
  assets/webconfig/js/content_instcapture.js
  include/hyperion/CaptureCont.h
  include/hyperion/Hyperion.h
  libsrc/hyperion/CaptureCont.cpp
  libsrc/hyperion/Hyperion.cpp
  libsrc/hyperion/schema/schema-instCapture.json
Labels: Enhancements

#1839 Add JSON-API support for requesting image snapshots
  CHANGELOG.md
  include/api/JsonAPI.h
  include/api/JsonApiCommand.h
  libsrc/api/JSONRPC_schema/schema-instancedata.json
  libsrc/api/JSONRPC_schema/schema.json
  libsrc/api/JSONRPC_schemas.qrc
  libsrc/api/JsonAPI.cpp
Labels: New Feature Request
